# Generated by Django 4.2.4 on 2023-08-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre_santes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='static/images/centre_sante')),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('localisation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Epidemies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=500, null=True)),
                ('traitement', models.CharField(blank=True, max_length=255, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_cas', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_mort', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maladies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=500, null=True)),
                ('traitement', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
