# Generated by Django 4.2.4 on 2023-09-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladies',
            name='epidemie',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medecine.epidemies'),
        ),
    ]
