# Generated by Django 4.2.4 on 2023-08-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='description',
            field=models.TextField(),
        ),
    ]
