# Generated by Django 4.2.4 on 2023-08-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_pharmacie_status_alter_pharmacie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
