# Generated by Django 4.2.4 on 2023-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_famille', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('chef_de_famille', models.CharField(max_length=100)),
                ('nombre_de_membres', models.PositiveIntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
