# Generated by Django 4.2.4 on 2023-08-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplois', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeemploi',
            old_name='auteur',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='demandeemploi',
            name='date_fin',
        ),
    ]
