# Generated by Django 4.2.4 on 2023-08-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplois', '0003_remove_demandeemploi_prix_semaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entrep', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=200)),
                ('nombre_place', models.IntegerField()),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance')], max_length=100)),
                ('description_offre', models.CharField(max_length=500)),
                ('competences_requises', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/images/offre_emplois/')),
                ('localisation', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='demandeemploi',
            name='photo',
            field=models.ImageField(upload_to='static/images/demande_emplois/'),
        ),
    ]
