# Generated by Django 4.2.4 on 2023-08-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Naissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_nouvau_nee', models.CharField(max_length=255)),
                ('date_naiss', models.DateField()),
                ('nom_du_pere', models.CharField(max_length=255)),
                ('nom_dela_mere', models.CharField(max_length=255)),
                ('lieu_habitation', models.CharField(max_length=1000)),
                ('mode_naisance', models.CharField(choices=[('H', 'hopital'), ('Q', 'quartier')], max_length=20)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
