# Generated by Django 4.2.4 on 2023-08-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_de_vie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_defun', models.CharField(max_length=255)),
                ('function', models.CharField(max_length=255)),
                ('date_naiss', models.DateField()),
                ('date_deces', models.DateField()),
                ('raison_deces', models.TextField()),
                ('mode_deces', models.CharField(choices=[('H', 'hopital'), ('Q', 'quartier')], max_length=20)),
                ('lieu_habitation', models.CharField(max_length=1000)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=20)),
                ('nom_parent_ref', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
