# Generated by Django 4.2.4 on 2023-08-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naiss', models.DateField(blank=True, null=True)),
                ('provenance', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_heber', models.CharField(blank=True, choices=[('nouvelle habitation', 'Nouvelle Habitation'), ('chez parent', 'Chez Un Parent')], max_length=255, null=True)),
                ('nom_parent_acc', models.CharField(blank=True, max_length=255, null=True)),
                ('lieu_habitation_fami', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
