# Generated by Django 4.2.4 on 2023-08-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenagement',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
