# Generated by Django 4.2.4 on 2023-08-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacement', '0002_amenagement_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naiss', models.DateField(blank=True, null=True)),
                ('nouvelle_dest', models.CharField(blank=True, max_length=255, null=True)),
                ('lieu_habitation_fami', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.BooleanField(default=False)),
            ],
        ),
    ]
