# Generated by Django 4.2.4 on 2023-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='date_naiss',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='lieu_naiss',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
