# Generated by Django 4.2.4 on 2023-09-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0001_initial'),
        ('familles', '0001_initial'),
        ('compte', '0002_alter_acteur_date_naiss_alter_acteur_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteur',
            name='famille',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acteurs', to='familles.famille'),
        ),
        migrations.AddField(
            model_name='acteur',
            name='maladie',
            field=models.ManyToManyField(related_name='acteurs', to='medecine.maladies'),
        ),
    ]
