# Generated by Django 4.2.4 on 2023-09-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autre', '0001_initial'),
        ('compte', '0003_acteur_famille_acteur_maladie'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteur',
            name='competence',
            field=models.ManyToManyField(related_name='competence', to='autre.competence'),
        ),
        migrations.AddField(
            model_name='acteur',
            name='metier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metier', to='autre.metier'),
        ),
    ]
