# Generated by Django 4.2.4 on 2023-09-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autre', '0001_initial'),
        ('familles', '0001_initial'),
        ('medecine', '0002_maladies_epidemie'),
        ('compte', '0004_acteur_competence_acteur_metier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='competence',
            field=models.ManyToManyField(blank=True, null=True, related_name='competence', to='autre.competence'),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='famille',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='famille', to='familles.famille'),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='maladie',
            field=models.ManyToManyField(blank=True, null=True, related_name='maladie', to='medecine.maladies'),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='metier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metier', to='autre.metier'),
        ),
    ]
