# Generated by Django 4.2.5 on 2023-10-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0002_maladies_epidemie'),
        ('deplacement', '0003_denagement'),
        ('pharmacie', '0003_alter_pharmacie_status'),
        ('compte', '0005_alter_acteur_competence_alter_acteur_famille_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acteur',
            old_name='sexe',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='acteur',
            name='amenager',
            field=models.ManyToManyField(blank=True, null=True, related_name='amenager', to='deplacement.amenagement'),
        ),
        migrations.AddField(
            model_name='acteur',
            name='centre_sante',
            field=models.ManyToManyField(blank=True, null=True, related_name='competence', to='medecine.centre_santes'),
        ),
        migrations.AddField(
            model_name='acteur',
            name='demenager',
            field=models.ManyToManyField(blank=True, null=True, related_name='demenager', to='deplacement.denagement'),
        ),
        migrations.AddField(
            model_name='acteur',
            name='pharmacie',
            field=models.ManyToManyField(blank=True, null=True, related_name='maladies', to='pharmacie.pharmacie'),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='date_naiss',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/user'),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='lieu_naiss',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
